In [1]:
import numpy as np

In [6]:
np.random.rand(20)

array([0.97215971, 0.22100622, 0.01168781, 0.3621305 , 0.22640112,
       0.47741138, 0.35128463, 0.35927543, 0.78621687, 0.58466836,
       0.45850037, 0.52383432, 0.88690072, 0.9565778 , 0.91475337,
       0.58496674, 0.25126691, 0.43863948, 0.88521078, 0.61348247])

In [17]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
x = np.arange(3,20)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
x = np.array([[0],[3]])
x

array([[0],
       [3]])

In [38]:
x = np.random.randint(100,1000,10)
x * 1000

array([665000, 399000, 679000, 905000, 444000, 275000, 929000, 660000,
       869000, 867000])