## numpy

In [6]:
import numpy as np

## array

In [7]:
a = np.array([1,12,33])
print(a)

[ 1 12 33]


In [8]:
aa = np.array([[1,1,1,1,1,1,1,1],[2,2,2,2,2,2,2,2],[3,3,3,3,3,3,3,3]])

In [9]:
aa.shape[0]

3

In [10]:
aa.shape[1]

8

In [11]:
aa.shape

(3, 8)

In [12]:
aa.reshape(3,8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3]])

## 1行にして表示

In [13]:
aa.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3])

In [15]:
print(aa)

[[1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]]


In [16]:
aa.shape

(3, 8)

In [18]:
aa.reshape(2,12)

array([[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2],
       [2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3]])

In [20]:
aa.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3])

In [37]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])